version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db1-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle-data:/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: password
volumes:
  db1-data:
  bundle-data:
